FROM node:14-alpine

# Create app directory
RUN mkdir -p /app
WORKDIR /app


# Bundle app source
COPY . /app
RUN yarn install
RUN yarn run build

EXPOSE 3005

# Starting command for the container upon startup
CMD sleep infinity